### ISSUE TITLE
Empty exports

### ISSUE THREAD

**Issue by agssl** [mpetroff/print-maps#18] opened 2018-12-06 07:36 UTC
Hi, thanks for your great work. It looks like it's exactly the tool I need right now.
Unfortunately my exports are always empty. It doesn't matter if PNG or PDF and it's also the same if I try to export an image from your demo @ https://printmaps.mpetroff.net/ (I'm running on macOS Mojave 10.14). 

Do you have an idea?

**Comment by mpetroff** [comment] 2018-12-06 17:50
What browser / browser version are you using?

**Comment by agssl** [comment] 2018-12-07 07:38
I ususally use Chrome and it's also not working in Safari for me. But I just tried in in Firefox and it works well there.

**Comment by mpetroff** [comment] 2018-12-07 22:11
It sounds like some sort of strange WebGL compatibility issue (something I'd expect from Safari, not Chrome).

Can you check to see if any error messages / warnings were printed to the browser's JavaScript developer console?

**Comment by agssl** [comment] 2018-12-10 08:22
No, there are no errors in the console. I think it depends to the pixel convertion or the pdf export. I took the relevant pieces from your code, which I need to create custom PNGs and created my own script and it works also in Chrome and Safari (mainly the the toBlob -> saveAs part).

**Comment by mpetroff** [comment] 2018-12-12 22:42
I was able to reproduce this with Safari 12 on macOS 10.13 via Sauce Labs, although I still don't know what's causing it.

I have a 2010 Mac Pro that I sometimes use for testing in Safari, but it tried updating itself to 10.14 despite not having a Metal-compatible graphics card, so it's out of commission until I get around to reinstalling 10.13 (or replacing the graphics card). I can't do any serious debugging in Safari until I fix that.

**Comment by mauriciovillam** [comment] 2018-12-19 17:20
Seconded, Safari 12.0.1 on macOS 10.13.6 and google chrome.

canvas.toDataURL() seems to generate a blank image, and in this project, the toBlob also seems to be generating a blank image.

**Comment by mauriciovillam** [comment] 2018-12-19 18:04
Apparently this is fixed by setting preserveDrawingBuffer option to true in mapboxgl.Map() initialization. Cheers @mpetroff!

**Closed as completed** 2018-12-20 01:08 UTC

**Comment by mpetroff** [comment] 2018-12-20 01:15
It broke when I updated Mapbox GL JS a month ago in d18430c1d51598c1e4f7fa7a45e6ccf1700c73ad, and I apparently only verified the update with Firefox. Since `preserveDrawingBuffer` has been set to `false` for years in Mapbox GL JS, it's actually pretty amazing that it's worked up until this point.
